### ISSUE TITLE
Crash at levelup armor equiped by mob

### ISSUE THREAD

**Issue by VladimirMangos** [TheMarstonConnell/randomlootmod#27]
java.lang.ClassCastException: net.tangotek.tektopia.entities.EntityGuard cannot be cast to net.minecraft.entity.player.EntityPlayer
	at com.mic.randomloot.init.ItemFields.upgrade(ItemFields.java:330)
	at com.mic.randomloot.items.RandomArmor.xpUp(RandomArmor.java:79)
	at com.mic.randomloot.util.handlers.RegistryHandler.playerHurt(RegistryHandler.java:244)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1715_RegistryHandler_playerHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at farseek.world.gen.structure.package$.post(package.scala:38)
	at farseek.world.gen.structure.package.post(package.scala)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.tangotek.tektopia.entities.EntityVillagerTek.func_70097_a(EntityVillagerTek.java:1422)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheMarstonConnell** [comment]
Did you intentionally put armor on this mob or did it happen by accident?

**Comment by VladimirMangos** [comment]
tektopia's guard mobs get armor from chests and equip by own choice.

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.4
