### ISSUE TITLE
Crashing on world load

### ISSUE THREAD

**Issue by TheGrimmSheeper** [TheMarstonConnell/randomlootmod#42]
I just downloaded the mod and it sounds really cool but i havent gotten a chance to use it because every time i try to load a world it crashes. Ive made it so that this is the only installed mod in my mod file and it crashes but when its not there its perfectly fine. Im using the 1.16.1 version and it happens when i load any world even a new world so please help me because this mod sounds pretty fun.

**Comment by Zedrimar** [comment]
can confirm. The applicable error seems to be from this: 

[01:33:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
	at xyz.marstonconnell.randomloot.RandomLootMod.onServerStarting(RandomLootMod.java:197) ~[?:2.1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_12_RandomLootMod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:65) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$9016/898353296.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

Full log: https://pastebin.com/T6XF25R5

Still no idea what causes it. I tested it by itself, works just fine. Added a few mods, worked just fine. Last known working version of forge for this was *.66. Anything past that (especially *.68+) had experienced error on world load. I really really don't wanna remove this mod so if there is a fix, that would be great! ^-^

**Comment by TheMarstonConnell** [comment]
Fixed in 2.1.1
