### ISSUE TITLE
 Exception caught during firing event: net.minecraft.item.AirItem cannot be cast to xyz.marstonconnell.randomloot.tools.IRLTool

### ISSUE THREAD

**Issue by shenniko** [TheMarstonConnell/randomlootmod#61]
getting an error with the below.. It stops any items from being dropped.. either by mining or dropping by hand.

[20:42:04] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.item.AirItem cannot be cast to xyz.marstonconnell.randomloot.tools.IRLTool
	Index: 8
	Listeners:
		0: NORMAL
		1: ASM: class com.direwolf20.buildinggadgets.common.events.BreakEventHandler GetDrops(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2646/970591815@5cc63112
		3: ASM: com.feed_the_beast.mods.ftbchunks.FTBChunks@54fe0267 blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2646/970591815@1306c89e
		5: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeListener@1b15a263 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		6: ASM: de.maxhenkel.car.events.BlockEvents@512dc03b breakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		7: LOW
		8: ASM: com.feed_the_beast.mods.ftbultimine.FTBUltimine@353ae267 blockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		9: LOWEST
		10: ASM: blusunrize.immersiveengineering.common.EventHandler@1e91bf1c breakLast(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to xyz.marstonconnell.randomloot.tools.IRLTool
	at xyz.marstonconnell.randomloot.init.ItemFactory.giftNewTrait(ItemFactory.java:37)
	at xyz.marstonconnell.randomloot.init.ItemFactory.applyToken(ItemFactory.java:22)
	at xyz.marstonconnell.randomloot.tools.BaseTool.upgradeTool(BaseTool.java:68)
	at xyz.marstonconnell.randomloot.tools.BaseTool.changeXP(BaseTool.java:59)
	at xyz.marstonconnell.randomloot.tools.RLToolItem.func_179218_a(RLToolItem.java:90)
	at xyz.marstonconnell.randomloot.tools.RLPickaxeItem.func_179218_a(RLPickaxeItem.java:216)
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:327)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:251)
	at com.feed_the_beast.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:176)
	at net.minecraftforge.eventbus.ASMEventHandler_284_FTBUltimine_blockBroken_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230)
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:860)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at java.lang.Thread.run(Thread.java:748)

[20:42:04] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to xyz.marstonconnell.randomloot.tools.IRLTool
	at xyz.marstonconnell.randomloot.init.ItemFactory.giftNewTrait(ItemFactory.java:37) ~[?:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.init.ItemFactory.applyToken(ItemFactory.java:22) ~[?:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.BaseTool.upgradeTool(BaseTool.java:68) ~[?:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.BaseTool.changeXP(BaseTool.java:59) ~[?:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.RLToolItem.func_179218_a(RLToolItem.java:90) ~[?:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.RLPickaxeItem.func_179218_a(RLPickaxeItem.java:216) ~[?:2.1.7] {re:classloading}
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:327) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:251) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:176) ~[?:1.1.0.10] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_284_FTBUltimine_blockBroken_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:860) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_action_fix}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
[20:42:18] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2414ms or 48 ticks behind
[20:42:48] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2103ms or 42 ticks behind
>

**Comment by TheMarstonConnell** [comment]
Should be fixed in 2.1.8, if not reopen this thread :)
