### ISSUE TITLE
(1.16.3) Breaks server to where items don't drop

### ISSUE THREAD

**Issue by bobeast731** [TheMarstonConnell/randomlootmod#65]
Whenever tools from this mod breaks , items no longer dropped to the ground till I restart the server.

**Comment by aharrisw** [comment]
Same thing just happened to me. Here's the debug entry-

`[07Dec2020 17:56:51.391] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: class net.minecraft.item.AirItem cannot be cast to class xyz.marstonconnell.randomloot.tools.IRLTool (net.minecraft.item.AirItem and xyz.marstonconnell.randomloot.tools.IRLTool are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @32245b66)
	at xyz.marstonconnell.randomloot.tools.BaseTool.setLore(BaseTool.java:102) ~[randomloot:2.1.7]
	at xyz.marstonconnell.randomloot.tools.BaseTool.setLore(BaseTool.java:72) ~[randomloot:2.1.7]
	at xyz.marstonconnell.randomloot.tools.RLToolItem.func_179218_a(RLToolItem.java:92) ~[randomloot:2.1.7]
	at xyz.marstonconnell.randomloot.tools.RLPickaxeItem.func_179218_a(RLPickaxeItem.java:216) ~[randomloot:2.1.7]
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:327) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:251) ~[?:?]
	at com.feed_the_beast.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:176) ~[ftbultimine:1603.1.1.12]
	at net.minecraftforge.eventbus.ASMEventHandler_506_FTBUltimine_blockBroken_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:860) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]`

**Comment by aharrisw** [comment]
Another stacktrace from the crashes.:

`-- Head --
Thread: Server thread
Stacktrace:
	at xyz.marstonconnell.randomloot.tags.worldinteract.DamageEvent.effect(DamageEvent.java:21) ~[randomloot:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tags.WorldInteractTag.runEffect(WorldInteractTag.java:30) ~[randomloot:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.RLToolItem.func_179218_a(RLToolItem.java:105) ~[randomloot:2.1.7] {re:classloading}
	at xyz.marstonconnell.randomloot.tools.RLAxeItem.func_179218_a(RLAxeItem.java:281) ~[randomloot:2.1.7] {re:classloading}
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:327) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:251) ~[?:?] {re:computing_frames,re:classloading}
	at com.feed_the_beast.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:176) ~[ftbultimine:1603.1.1.12] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_544_FTBUltimine_blockBroken_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561) ~[forge:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:96) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:350) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}`

**Comment by TheMarstonConnell** [comment]
Could be fixed in 2.1.8. Please try it an reopen this.

**Comment by freevortex** [comment]
I'm still getting this using 2.3.9.
