### ISSUE TITLE
Crash when opening the bag [1.12.2]

### ISSUE THREAD

**Issue by kellixon** [TheMarstonConnell/randomlootmod#67]
MC 1.12.2. Forge 14.23.5.2854. RandomLoot 1.7.4. Crash when opening the bag. Appeared recently, now after opening any bag crash. Debag attached, information about the crash at the end of the document.
[debug.log](https://github.com/TheMarstonConnell/randomlootmod/files/5560637/debug.log)
`Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.player.InventoryPlayer.add(InventoryPlayer.java:383)
    at net.minecraft.entity.player.InventoryPlayer.addItemStackToInventory(InventoryPlayer.java:378)
    at com.mic.randomloot.util.handlers.messages.MessageHandler.lambda$onMessage$0(MessageHandler.java:33)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more`

**Comment by TheMarstonConnell** [comment]
Unfortunately 1.12 is no longer supported. Sorry.
